# GET http://localhost:6000/api
# GET http://localhost:6000/api/621cc97016fa04f873832856
# POST http://localhost:6000/api/

PUT http://localhost:6000/api/621cc97016fa04f873832856
Content-Type: application/json


{
    "firstName": "Eden", 
    "lastName": "Tasama",
    "age": 25,
    "email" : "lalala"
}


